# Copyright Altoros. All Rights Reserved.
#

version: '2'
services:

  base:
    image: node:6-alpine
    environment:
      - FOLDER_SAVE=${FOLDER_SAVE}
    volumes:
      - ./:/usr/src
    working_dir: /usr/src