#
# Copyright Altoros. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  sign.a.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.a.nsd.ru
    environment:
      - API=http://api.a.nsd.ru:4000
    command: npm run sign

  sign.b.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.b.nsd.ru
    environment:
      - API=http://api.b.nsd.ru:4000
    command: npm run sign

  sign.c.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.c.nsd.ru
    environment:
      - API=http://api.c.nsd.ru:4000
    command: npm run sign

  download.nsd.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: download.nsd.nsd.ru
    environment:
      - API=http://api.nsd.nsd.ru:4000
    command: npm run download

networks:
  default:
    external:
      name: ledger_default
