#
# Copyright Altoros. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  sign.raiffeisen.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.raiffeisen.nsd.ru
    environment:
      - API=http://api.raiffeisen.nsd.ru:4000
    command: npm run sign

  sign.megafon.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.megafon.nsd.ru
    environment:
      - API=http://api.megafon.nsd.ru:4000
    command: npm run sign

  sign.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: sign.${THIS_ORG}.nsd.ru
    environment:
      - API=http://api.${THIS_ORG}.nsd.ru:4000
    command: npm run sign



  download.nsd.nsd.ru:
    extends:
      file:   base.yaml
      service: base
    container_name: download.nsd.nsd.ru
    environment:
      - API=http://api.nsd.nsd.ru:4000
    command: npm run download



  static.nsd.nsd.ru:
    extends:
      file:   base.yaml
      service: base-static
    container_name: static.nsd.nsd.ru

  static.raiffeisen.nsd.ru:
    extends:
      file:   base.yaml
      service: base-static
    container_name: static.raiffeisen.nsd.ru

  static.megafon.nsd.ru:
    extends:
      file:   base.yaml
      service: base-static
    container_name: static.megafon.nsd.ru

networks:
  default:
    external:
      name: dockercompose_default
